apiVersion: v1
kind: Service
metadata:
  name: harness-pipelines-service
spec:
  selector:
    app: harness-pipelines
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
